config/routes.rb
Rails.application.routes.draw do
  get 'images/home' , :action => "home", :controller => "images"
  
  get 'images/azure_sas_uri', :action => "azure_sas_uri", :controller => "images"
  post 'images/azure_success', :action => "azure_success", :controller => "images"

  get 'login/new'

  get 'elements/build'

  get 'element/build'

  resources :units
  
  resources :lists, except: [:index,:new,:create,:show,:edit,:update] do 
    collection do 
      get 'element_spam_list'
    end
  end

  get 'categories/search'

  resources :tests, only: [:index,:new,:create,:show,:edit,:update] do
    collection do 
      get 'change'
    end
  end

  root 'home#index'

  resources :categories do 
    collection do 
      get 'search/:q', :action => "search", :as => 'search'
    end
  end

  

  resources :corners do 
    
  end

  resources :elements do 
    collection do 
      post 'edit_image'
    end
  end

  resources :reports, only: [:new]

  resources :home, only: [:index]

  

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" , :registrations => "users/registrations", :confirmations => "users/confirmations", :passwords => "users/passwords", :sessions => "users/sessions"}

  resources :users, except: [:show, :edit, :update, :destroy, :index, :new, :create] do

    collection do
        get 'sign_in_failed','email_exists','nickname_exists','password_strength','oauth_sign_in_failed','email_matches_current'
    end

    get 'profile', on: :member
  
  end

  

  resources :topics do 
    collection do
      get 'search/:q', :action => "search", :as => 'search'
    end
  end

end

app/models/corner.rb
class Corner < Element

  field :score,                         type: Float, default: 1.0
 
  def self.build(options={},current_user)
    if id_is_valid?(options)
      _element = self.find_or_initialize_by(Hash["_id",options.fetch("_id").to_s])
      attributes_to_persist,_element = assign_attributes(options,_element,current_user)
      _element = persist(attributes_to_persist,_element)
    else
      _element = self.new
      _element.errors.add(:_id,"the provided id is invalid")
    end
    return _element
  end

end

app/controllers/corners_controller.rb
class CornersController < ElementsController

  respond_to :js,:html

  def index

    @corner = Corner.order_by(:created_at => 'desc').first
    redirect_to corner_path(@corner)

  end


  def new
   
      @r = Response.new
      @r.corner = Corner.new
      @r.units = [Unit.new]
      @r.errors = {}
      @r.messages = {}
   
  
  end


  def edit

    @corner = Corner.find(params[:id])

  end

  def show
    @r = Response.new
    e = Element.any_of({:corner_id => BSON::ObjectId(params[:id])},{:id => BSON::ObjectId(params[:id])}).order_by(:score => "desc")

    @r.corner = e[0]
    
    ##this should be sorted by score.
    @r.units = e[1..-1]
    #puts "r corner is:"
    #puts JSON.pretty_generate(@r.corner.attributes)
    #puts "units are"
    @r.units.each do |u|
    #puts JSON.pretty_generate(u.attributes)
    end
    #gets.chomp
    if @r.corner
      puts "the corner contributor ids are:"
      puts @r.corner.contributor_ids.to_s
      @r.creator = User.find(@r.corner.contributor_ids.last[0])
    end

    render :template => "corners/new"
  end


  ##this was called on create if there was not registered user.
  def add_to_db
    current_user ?  process_element(session[:pending] ? session[:pending] : create_permit_params) : add_params_to_session(create_permit_params)
  end


 
end

app/helpers/corners_helper.rb
module CornersHelper

	
	## @used_in: corners/_card_reveal.html.erb
	## 		   : spam_changed.js.erb
	## @param[Element] el : the current element
	## @param[User] user : the current user
	## @param[Integer] count : the count of the spammed attribute
	## @param[String] attribute_marked_for_spam : the attribute marked for spam namely -> title/content/link/image
	## @returns[String] : a string saying how many people have marked this attribute as spam.
	def n_users_marked_this_as_spam(el,curr_usr,count,attribute_marked_for_spam)
		#puts "count is: #{count}"
		#puts "type is: #{attribute_marked_for_spam}"
		#puts "title contributor ids"
		#puts el.title_spam_contributor_ids

		#puts "content contributor ids"
		#puts el.content_spam_contributor_ids

		if el.attribute_marked_for_spam_contains_curr_usr(attribute_marked_for_spam,curr_usr)
			if count == 1
				"You marked this as spam" 
			elsif count == 2
				"You and 1 other person marked this as spam"
			elsif count > 2
				"You and " + ("other".pluralize(count - 1)) + " marked this as spam"
			else
				""
			end
		else
			
			if count > 0
				"user".pluralize(count) + " marked this as spam"
			else
				""
			end
		end
	end


	## @used_in:corners/_spam_changed.js.erb
	## @param[Element] : the current element.
	## @param[User] : the curr_usr
	## @return[String] : this is basically a hash that has been jsonified, 
	## it has the following structure:
	## two basic keys
	## =>  total - always contains only one key
	## i.e the id of the span element, that is seen in the options bar, under the spam_icon, which shows the total spam_count for this element.
	## the value of this key is the total_spam_count for this element.
	## =>  individual - always contains only one key.
	## i.e the id of the spam_icon in the card reveal spam_table.
	## the value of this key is either true/false, depending on whether the current user has marked in the previous commit an attribute for spam.
	def spam_details(el,curr_usr)
		attribute_marked_for_spam = el.get_spammed_attribute
		total_spam_count = el.get_total_spam_count
		response = {}
		response["total"] = {}
		response["total"][el.id.to_s + "_spam_count_"] = total_spam_count
		response["individual"] = {}
		response["individual"][el.id.to_s + "_spam_icon_" + attribute_marked_for_spam] = el.attribute_marked_for_spam_contains_curr_usr(attribute_marked_for_spam,curr_usr)
		JSON.generate(response).html_safe
	end

	

	

	## @used_in:corners/_corner_created.js.erb
	## In case spam is incremented, we do not re-render the corner and units.
	## We only increment the requisite attribute for which spam was marked.
	## Checks each spam attribute to see if it was changed.
	## logic used is to flatten corner and units into a single array, remove any nil elements, and keep those elements which have a spam_contributor_attribute present in the previous_changes of the element.
	## previous_changes is a rails method that performs dirty tracking.
	## for this we call a method in the Element.rb file called spam_attributes_added.
	## @param[Corner] c : Corner element
	## @param[Array] units: Array of Unit elements
	## @return[Element] : returns first element out of array of elements, which have had their spam attributes changed.
	def spam_attributes_changed?(c,units)
		[c,units].flatten.compact.keep_if{|c|
			c.spam_attributes_added.size > 0
		}[0]
	end

	## @used_in: corners/_card_reveal.html.erb
	## Decides whether a table row should be shown or not.
	## While deciding to show the table rows , we only want to show rows for those attributes which exist. 
	## The problem with images is that, if there is no image, then the placeholder image url becomes /missing.png. 
	## So it passes the check for the val[0] to exist, falsely.
	## So for images we further add a check to see if has_image? returns true.
	## In case of other attributes, as long as the val[0] exists, we return true.
	## @param[Array] val : Consists of two elements, at zero position is the  attribute value and and position one is the attribute name . eg: [title_value,"title"]
	## @param[Element] : the corner or unit.
	## @return[Boolean] : if the attribute value is nil, then false. If the attribute value is not nil, then if it is an image and an image exists -> then true, otherwise true.
	def show_spam_row(val,c)
		if val[0]
			if val[1] == "image"
				c.has_image?
			else
				true
			end
		else
			false
		end
	end

	## @used_in: corners/_spam_icon.html.erb
	## @param[Element] c : instance of Element , that is to be rendered in the view
	## @param[String] type : either "image","title","content","link"
	## @return[String] : the id of the attribute, or empty string "" if no id exists.
	def get_attribute_id(c,type)
		type_id = type + "_id"
		if tid = c.send(type_id)
			tid
		else
			""
		end
	end

end

app/views/corners/_add_a_link_modal.html.erb
<div id="add_a_link_modal" class="modal bottom-sheet">
	<div class="modal-content">
	  <h4 class="text-darken-2">Paste Link
	   <i class="mdi-content-clear right cursor-pointer modal-close" data-modal-id="add_a_link_modal"></i>
	  </h4>
	  <input type="text" id="link" style="width:50%" value="" placeholder="Enter the link"/>
	  <input type="text" id="link-title" style="width:50%" placeholder="Enter a title for your link" />
	  <br />
	  <div id="link-error-message" class="m-0-top fs-12 blue-grey-text text-darken-2 fw-500" style="display:none;"><i class="mdi-alert-error grey-text text-lighten-1"></i>That link is invalid</div>
	  <button class="btn waves-effect waves-light m-20-top modal-close">Save</button>
	</div>
	<div style="height:30px"></div>
</div>

app/views/corners/_card_reveal.html.erb
<div class="card-reveal p-40-bottom" style="width:100%; padding-left:0px; padding-top:5px; overflow-y: visible; display:block;" id="<%= c.id.to_s %>_reveal" data-element-id="<%= c.id.to_s %>">
  <span class="card-title grey-text text-darken-4 p-20-top">Help Us With Spam!<i></i></span>

  <table class="bordered" id="<%= c.id.to_s %>_table" data-element-id="<%= c.id.to_s %>">
        <thead>
          <tr>
              <th data-element-th=""></th>
              <th data-element-th=""></th>
          </tr>
        </thead>
        <tbody>
          <% [[c.image.url,"image"],[c.title,"title"],[c.content,"content"],[c.link,"link"]].each do |val| %>
              <% if show_spam_row(val,c) %>
                <tr class="reveal_row">
                  <td class="p-20-left">
                    <div>
                      <% if val[1] == "image" %>
                          <% if c.has_image? %>
                            <img src="<%= val[0] %>" height="40px" width="40px" />
                          <% end %>
                      <% else %>
                        <%= truncate(val[0].to_s, length: 70) %>
                      <% end %>
                    </div>
                    <% count = c.has_spam(val[1]) %>
                    <div class="grey-text text-darken-2">
                        <span class="users_list_activator" id="<%= c.id.to_s + "_" + val[1] + "_spam_contributors_list" %>" data-element-id="<%= c.id.to_s %>" data-corner-id="<%= corner_id %>" data-attribute-type="<%= val[1] %>"><%= n_users_marked_this_as_spam(c,current_user,count,val[1]) %></span>
                    </div>
                  </td>
                  <td>
                    <%= render :partial => "corners/spam_icon.html.erb", locals: {:c => c, :type => val[1], :corner_id => corner_id, location: "spam_table"} %>
                  </td>
                </tr>
              <% end %>
          <% end %>
        </tbody>
 </table>
 <div class="p-20-bottom m-20-top fs-12 blue-grey-text text-lighten-2 deactivator" data-element-id="<%= c.id.to_s %>">Dismiss</div>
 <div class="card-reveal-bottom-marker" data-element-id="<%= c.id.to_s %>">
 </div>
</div>

app/views/corners/_corner.html.erb
<!--

title -> corner/unit.id.to_s_title
content -> corner/unit.id.to_s_content
image->not sent with create/update.
link->corner/unit.id.to_s_link
weather->unit.id.to_s_weather


-->
<div data-corner-id="<%= corner.id.to_s %>" class="section scrollspy m-5-bottom p-0-bottom p-0-top" id="scrollspy_about"></div>


  <% show_permissions = get_show_permissions(corner,"intro") %>
  <!-- debug showing permissions for intro -->
  
  <div data-corner-id="<%= corner.id.to_s %>" class="row m-0-bottom">
    <h3 data-corner-id="<%= corner.id.to_s %>" class="m-10-bottom col l7 m-0-top m-0-bottom p-0-bottom p-0-top">
    
    <%= render :partial => '/corners/corner_about_holder.html.erb', locals:{c: corner, p: show_permissions} %>
    
    <div data-corner-id="<%= corner.id.to_s %>" class="fs-18 grey-text text-lighten-2" style="line-height:1.1;" id="about_example">
     <%= render :partial => "/corners/corner_creator.html.erb", locals:{c: corner, created_time: corner.new_record? ? Time.now : corner.created_at, p: show_permissions} %>
    </div>
    
    </h3>
    <div data-corner-id="<%= corner.id.to_s %>" class="col l1">
        <i data-corner-id="<%= corner.id.to_s %>" class="title_warning mdi-alert-error red-text text-darken-1 icon-tooltip fs-30 p-5-top" style="display:none;" id="corner_title_invalid" title="Add A Title"></i>  
    </div>
  </div>

  <!--<i data-corner-id="<%= corner.id.to_s %>" class="mdi-action-check-circle green-text fs-30"></i>-->
  <!--<i data-corner-id="<%= corner.id.to_s %>" class="mdi-content-link blue-grey-text fs-30"></i>-->
  
  <!-- title ends -->
  <div data-corner-id="<%= corner.id.to_s %>" class="divider m-10-top m-10-bottom"></div>
  <!-- body -->
  

  
  <div data-corner-id="<%= corner.id.to_s %>" class="row p-10-left m-20-bottom">

  	<div data-corner-id="<%= corner.id.to_s %>" class="col l9 m12 s12" id="units_holder">
      
        <%= render :partial => "/corners/corner_or_unit_holder.html.erb", locals: {c: corner, p: show_permissions, intro: true, parent_corner: nil} %>
        
        <% if !unit_arr.empty? %>
          
          <% unit_arr.each do |u| %>
            
            <%= render :partial => "/corners/corner_or_unit_holder.html.erb", locals: {c: u, p: get_show_permissions(u,false), intro: false, parent_corner: corner} %>    
          <% end %>
        <% end %>
    </div>
    
  </div>

  



<div data-corner-id="<%= corner.id.to_s %>" class="row" id="add_new_section" style="cursor:pointer">
  <%= form_tag(new_unit_path, id:"add_new_section_form", method: "get", remote: true) do %>
    <%= hidden_field_tag "corner_id", corner.id.to_s, {:id => "add_new_section_corner_id_" + corner.id.to_s} %> 
    <div data-corner-id="<%= corner.id.to_s %>" class="col l1 m1 s1 p-10-top p-10-bottom center blue-grey-text text-darken-2 fw-300 fs-30 weather_holder m-10-left" style="border:1px solid gainsboro;" id="add-section">
      <i data-corner-id="<%= corner.id.to_s %>" class="mdi-av-playlist-add dull icon-tooltip" title="Add Section"></i>
    </div>
    <div data-corner-id="<%= corner.id.to_s %>" class="col l1 m1 s1 p-10-top p-10-bottom center blue-grey-text text-darken-2 fw-300 fs-30 weather_holder m-10-left publish" style="border:1px solid gainsboro;"  data-element-id = "<%= corner.id.to_s %>">
      <i data-corner-id="<%= corner.id.to_s %>" class="mdi-hardware-keyboard-tab dull icon-tooltip" data-element-id="<%= corner.id.to_s %>" title="Post"></i>
    </div>
  <% end %>
</div>

<div data-corner-id="<%= corner.id.to_s %>" class="divider"></div>
<div data-corner-id="<%= corner.id.to_s %>" style="display:none">

</div>
<%= render '/corners/upload_an_image_modal.html.erb' %>
<%= render '/corners/add_a_link_modal.html.erb' %>

app/views/corners/_corner_about.html.erb
<!-- partial variables: c -> corner, p -> permissions hash -->
<% if p["title"][:show_entity] || c.new_record? %>
<div data-corner-id="<%= c.id.to_s %>" class="row m-0-bottom" data-element-id="<%= c.id.to_s %>">

<div data-corner-id="<%= c.id.to_s %>" id="<%= c.id.to_s %>_type" data-is-a-corner= "<%= c.is_a_corner? ? 0 : 1 %>" style="display:none;" data-element-id="<%= c.id.to_s %>" data-title-id="<%= c.title_id.to_s %>" data-content-id="<%= c.content_id.to_s %>" data-image-id="<%= c.image_id.to_s %>" data-link-id="<%= c.link_id.to_s %>"></div>
    <div data-corner-id="<%= c.id.to_s %>" class="col l10 m10 s10 p-0-right" style="width:76.29%;">
      <div data-corner-id="<%= c.id.to_s %>" class="ctitle title <%= 
      
      if c.has_entity?("title")
      		"edited"
      else
      		"virgin"
      end

       %> m-10-bottom" 

      style="min-height:53px; padding-left:1px" 

      data-element-id="<%= c.id.to_s %>"
      
      id="<%= c.id.to_s %>_title" 
      
      placeholder="<%=
        if !c.has_entity?("title")
      		"Your Corner Is About"
      	end
      %>" 
      contenteditable="<%= p['title'][:change_or_add_entity] 
      %>" 
      data-placeholder="Your Corner is About"
      data-temp-value="<%=

          if c.has_entity?("title")
            c.title
          else
            ""
          end

       %>"
      ><%= 

      		if c.has_entity?("title")
      			c.title
      		end

       %><br>
      </div>
    </div>
    <% if p['title'][:change_or_add_entity] %>
    <div data-corner-id="<%= c.id.to_s %>" class="col l1 m1 s1">
      <i data-corner-id="<%= c.id.to_s %>" class="mdi-content-create fs-25 grey-text icon-tooltip" id="<%= c.id.to_s %>_example_icon" data-element-id="<%= c.id.to_s %>" data-edit-corner-icon = "<%= c.is_a_corner? %>" style="vertical-align:text-bottom;"></i>
    </div>
   
    <% end %>
</div>
<% end %>

app/views/corners/_corner_creator.html.erb
<% if !c.nil? && c.new_record? %>
		e.g Jogging
<% else %>
		<% 
		   ## if a corner is not there in the response, then check if we have units, and if we have units, then the element becomes the first unit, if we dont have units also, then the element remains nil, and if we do have a corner, then the element becomes the corner.
		   ##we need this element, to show the updated at last, and by.
		   
		   el = c.nil? ? (!units.nil? ? units[0] : nil) : c
		%>

		<% if !el.nil?
		   t = el.updated_at 
		   time_stub = epoch_to_readable(t.to_i)
		   updated_by_id = el.contributor_ids.last[0]
		   updater = User.find(BSON::ObjectId(updated_by_id))
		   updated_by_name = updater.name
		 %>
		 
			Updated by <%= link_to updated_by_name.to_s, profile_user_path(updated_by_id) %> <%= time_stub %>

		<% end %>
<% end %>

app/views/corners/_corner_or_unit_holder.html.erb
<div class="row <%= c.is_a_corner? ? "corner" : "unit" %>" data-element-id="<%= c.id.to_s %>" data-corner-id="<%= 

	if c.is_a_corner?
		c.id.to_s 
	else
		if parent_corner.nil?
			c.corner_id.to_s
		else
			parent_corner.id.to_s
		end
	end

 %>">
	<%= render :partial => "/corners/corner_or_unit.html.erb", locals: {c: c, p: p, intro: intro, parent_corner: parent_corner} %>
</div>

app/views/corners/_image_partial.html.erb
<img data-corner-id="<%= corner_id.to_s %>" src="<%= c.image.url(:cropped) %>" class="image" id="<%= c.id.to_s %>_image" data-element-id="<%= c.id.to_s %>" data-image-id="<%= c.image_id.to_s %>" /> 
<%= render :partial => "/corners/approve_disapprove.html.erb", locals:{c: c, type:"image", corner_id: corner_id.to_s} %>

app/views/corners/_options_bar.html.erb
<!-- c : corner or unit , p : permissions, type: link/image/content/title -->
<div data-corner-id="<%= corner_id.to_s %>" class="row m-0-bottom options_holder m-0-top" id="<%= c.id.to_s %>_options_holder">

	<div data-corner-id="<%= corner_id.to_s %>" class="col l6 offset-l3 m6 offset-m3 s6 offset-s3 center">

		<% if p[:show_spam_button] %>
			<%= render :partial => "corners/spam_icon.html.erb" , locals: {corner_id: corner_id, c: c, type: nil, location: "options_bar"}%>
		<% end %>

		<% if p["link"][:change_or_add_entity] %>
			<i data-corner-id="<%= corner_id.to_s %>" class="mdi-content-link<%=
			 if c.has_entity?("link")
			 	" amber-text"
			 else
			 	" grey-text text-lighten-2"
			 end
			 %> fs-15 options editable_links" title="Add Link" id="<%= c.id.to_s %>_add_link" data-element-id="<%= c.id.to_s %>" href="#add_a_link_modal" data-link-title-init-value="<%= c.link_title %>" data-link-init-value="<%= c.link %>" data-link="" data-link-title="" >
			 	
			 </i>
		<% end %>

		<% if c.is_a_unit?  &&  p["image"][:change_or_add_entity] %>
			<i data-corner-id="<%= corner_id.to_s %>" class="mdi-image-photo-camera grey-text text-lighten-2 fs-15 options editable_images" data-element-id="<%= c.id.to_s %>" href="#upload_an_image_modal" id="<%= c.id.to_s %>_add_image"></i>
		<% end %>

	</div>
	
</div>

app/views/corners/_upload_an_image_modal.html.erb
<div id="upload_an_image_modal" class="modal">
	<%= render :partial => "/modals/base_modal/base", :locals => {:modal_content => "/corners/upload_an_image_modal_content.html.erb", :modal_footer => nil, :modal_title => "", :namespace => "_upload_an_image"} %>
</div>

app/views/corners/_upload_an_image_modal_content.html.erb
<div class="row m-30-top">
	<div class="col l6 offset-l3 m6 offset-m3 s6 offset-s3">
		<input type="url" id="image_url" placeholder="Paste A Url" />
	</div>
	<div class="l1 p-10-top" id="image_url_submit" style="display:none;">
		<i class="mdi-action-trending-neutral teal-text text-darken-2 fs-25 icon-tooltip"  style="cursor:pointer;" title="Submit"></i>
	</div>
</div>
<div class="row">
	<div id="image-url-error-message" class="col l6 offset-l3 m6 offset-m3 s6 offset-s3 center m-0-top fs-12 red-text text-darken-2 fw-500" style="display:none;"><i class="mdi-alert-error grey-text text-lighten-1"></i>That url is invalid</div>
</div>
<div class="row center m-40-top fs-22 fw-200 teal-text">
	OR
</div>
<div class="row m-0-bottom" style="position:relative;">
	<div class="col l6 offset-l3 m6 offset-m3 s6 offset-s3 center">
		<i class="mdi-hardware-computer fs-100" style="margin-top:-20px; cursor:pointer;" id="upload_image_from_pc" data-opener-id></i>
	</div>
	<div class="col l6"></div>
	<div class="fw-200 fs-22" style="position:absolute; bottom:2%; left:31.5%;">
	Choose a file from your PC.
	</div>
</div>

app/views/corners/_validation_errors.html.erb
<% errors.each do |f,m| %>
	<div><%= f %></div>
	<div><%= m %></div>
<% end %>

app/views/corners/destroy.html.erb
<h1>Corners#destroy</h1>
<p>Find me in app/views/corners/destroy.html.erb</p>

app/views/corners/edit.html.erb
<%= form_for @corner do |f| %>
  about: <%= f.text_field :about %>

  <%= f.fields_for :units  do |builder| %>
         <%= builder.label :title %>
         <%= builder.text_field :title %>
  <% end %>
 
  <%= f.submit "Submit" %>
<% end %>

app/views/corners/update.html.erb
<h1>Corners#update</h1>
<p>Find me in app/views/corners/update.html.erb</p>