config/routes.rb
Rails.application.routes.draw do
  get 'images/home' , :action => "home", :controller => "images"
  
  get 'images/azure_sas_uri', :action => "azure_sas_uri", :controller => "images"
  post 'images/azure_success', :action => "azure_success", :controller => "images"

  get 'login/new'

  get 'elements/build'

  get 'element/build'

  resources :units
  
  resources :lists, except: [:index,:new,:create,:show,:edit,:update] do 
    collection do 
      get 'element_spam_list'
    end
  end

  get 'categories/search'

  resources :tests, only: [:index,:new,:create,:show,:edit,:update] do
    collection do 
      get 'change'
    end
  end

  root 'home#index'

  resources :categories do 
    collection do 
      get 'search/:q', :action => "search", :as => 'search'
    end
  end

  

  resources :corners do 
    
  end

  resources :elements do 
    collection do 
      post 'edit_image'
    end
  end

  resources :reports, only: [:new]

  resources :home, only: [:index]

  

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" , :registrations => "users/registrations", :confirmations => "users/confirmations", :passwords => "users/passwords", :sessions => "users/sessions"}

  resources :users, except: [:show, :edit, :update, :destroy, :index, :new, :create] do

    collection do
        get 'sign_in_failed','email_exists','nickname_exists','password_strength','oauth_sign_in_failed','email_matches_current'
    end

    get 'profile', on: :member
  
  end

  

  resources :topics do 
    collection do
      get 'search/:q', :action => "search", :as => 'search'
    end
  end

end

app/views/modals/_ajax_error_modal.html.erb
<div id="ajax_error_modal" class="modal">
	<%= render :partial => "/modals/base_modal/base", :locals => {:modal_content => "/modals/ajax_error_modal_content.html.erb", :modal_footer => nil, :modal_title => "Oops!", :namespace => "_ajax_error"} %>
</div>

app/views/modals/_edit_account_content.html.erb
<% if !resource.nil? %>
	<%= form_for(resource, as: resource.class.name.underscore, url: registration_path(resource.class.name.underscore), remote: true, :authenticity_token => true, data: {type: "script"}, html: {id: "login_form"}) do |f| %>
		<div class="row" id="login_inputs">
		  <div class="col l8 m10 s10 offset-l2 offset-m1 offset-s1">
		      <div class="input-field">
	            <input <%= 
	            	 if resource.identities.size > 0
	            	 	"disabled"
	            	 end
	             %> id="user_email" type="email" name="user[email]" class="virgin" autofocus="false" value="<%= 
	             	
	             		resource.email
	             	
	              %>"></input>
	            <label for="user_email" autofocus="false"><%=
	            if resource.identities.size == 0
	             "E-mail" 
	            end
	             %></label>
	          </div>
	          <% if resource.identities.size == 0 %>
		          <div class="input-field m-50-top">
		            <input id="user_password" type="password" name="user[password]" class="virgin"></input>
		            <label for="user_password">New Password</label>
		          </div>

		          <div class="input-field m-50-top">
		            <input id="user_password_confirmation" type="password" name="user[password_confirmation]"  class="virgin">
		            </input>
		            <label for="user_password_confirmation">Confirm New Password</label>
		          </div>

		          <div class="input-field m-50-top">
		            <input id="user_current_password" type="password" name="user[current_password]"  class="virgin">
		            </input>
		            <label for="user_current_password">Your Current PassWord</label>
		          </div>
	          <% end %>
	          <%= puts resource.identities.size %>
	          <%= render '/modals/oauth_and_submit.html.erb' %>

		  </div>
		</div>
		<%= f.submit "Update",  id: "login_submit", style: "display:none;" %>
	<% end %>
<% end %>

app/views/modals/_forgot_password_success_content.html.erb
<% if !resource.nil? %>
	<h5 class="teal-text fw-200 center m-0-top p-0-top">We sent an Email with instructions on changing your password to <%= content_tag(:span, resource.email,{:class => "pink-text text-darken-2 fw-400"}) %></h5>
	<div class="row m-30-top center">
		<div class="col l6 m12 s12 offset-l3">
			<i class="mdi-communication-email fs-150"></i>
		</div>
	</div>
<% end %>

app/views/modals/_login_default_content.html.erb
<div id="login_forms">
     
</div>

app/views/modals/_login_navigation_options.html.erb
<div class="row">
  <div class="col l6 m6 s12 offset-l3 offset-m3 center teal-text text-darken-2 fs-12">
    <div id="show_sign_up" class="cursor-pointer">Don't have an Account? Sign Up For Free</div>
    <div id="forgot_password" class="cursor-pointer">Forgot Your Password?</div>
    <div id="resend_confirmation_email" class="cursor-pointer">Resend Confirmation Email</div>
    
  </div>
</div>

app/views/modals/_oauth_and_submit.html.erb
<div class="m-50-top row m-0-left m-0-right m-0-bottom" id="oauth_and_submit">
  
  <div class="col l6 m6 s6 left p-0-left p-0-right" id="oauth_icons">
    <a href="/users/auth/facebook"><img src="/assets/facebook.svg" height="60" width="60"  class="oauth_icon"/></a>
    <a href="/users/auth/google_oauth2"><img src="/assets/google_plus.svg" height="60" width="60"   class="oauth_icon m-10-left"/></a>
  </div>
  
  <div class="col l6 m6 s6 p-0-left p-0-right" id="submit">
    
      <i class="mdi-hardware-keyboard-tab grey-text right cursor-pointer" style="height:60px; width:60px; border:1px solid #9e9e9e; border-radius:5px; font-size:1.8em; padding-top:0.75rem; text-align:center;" id="submit_icon"></i>
    
  </div>
</div>

app/views/modals/_resend_confirmation_content.html.erb
<h5 class="teal-text fw-200 center m-0-top p-0-top">Enter your Email Address</h5>
<% if !resource.nil? && resource.respond_to?("pending_reconfirmation?") %>
	<%= form_for(resource, as: resource.class.name.underscore, url: confirmation_path(resource.class.name.underscore), remote: true, :authenticity_token => true, data: {type: "script"}, html: { method: :post, id: "login_form" }) do |f| %>
	  <div class="row m-50-bottom">
	  	  <div class="col l6 m6 s12 offset-l3 offset-m3">
			  <div class="input-field m-30-top" style="margin-bottom:-30px;">
			    <input autofocus="autofocus" type="email" value="<%= (resource.pending_reconfirmation? ? resource.unconfirmed_email : resource.email) %>" name="user[email]" id="user_email">
			    <label for="user_email" class="">Email</label>
			  </div>
			  <%= render '/modals/oauth_and_submit.html.erb' %>
			  <div class="actions">
			    <%= f.submit "Resend confirmation instructions", style: "display:none;", id:"login_submit" %>
			  </div>
		  </div>
	  </div>
	<% end %>
<% end %>

app/views/modals/_resend_confirmation_success_content.html.erb
<% if !resource.nil? %>
	<h5 class="teal-text fw-200 center m-0-top p-0-top">We sent an Email with confirmation instructions to <%= content_tag(:span, resource.email,{:class => "pink-text text-darken-2 fw-400"}) %></h5>
	<div class="row m-30-top center">
		<div class="col l6 m12 s12 offset-l3">
			<i class="mdi-communication-email fs-150"></i>
		</div>
	</div>
<% end %>

app/views/modals/_sign_in_inputs.html.erb
<div id="sign_in_inputs">
  <div class="input-field">
    <input autofocus="autofocus" type="email" value="" name="user[email]" id="user_email">
    <label for="user_email" class="">Email</label>
  </div>
  <div class="input-field m-50-top">
    <input autocomplete="off" type="password" name="user[password]" id="user_password">
    <label for="user_password" class="">Password</label>
  </div>
</div>

app/views/modals/_sign_in_success_content.html.erb
<div class="row m-30-bottom">
  <div class="col l6 offset-l3 m6 s12 center">
  	<i class="teal-text mdi-action-thumb-up fs-100"></i>
  </div>
</div>

app/views/modals/_sign_up_inputs.html.erb
<div id="sign_up_inputs" style="display:none;">
  <div class="input-field m-50-top">
    <input autocomplete="off" type="password" name="user[password_confirmation]" id="user_password_confirmation">
    <label for="user_password_confirmation">Password confirmation</label>
  </div>
  <div style="text-align:center; padding-top:3rem;" id="recaptcha_tags">
    
  </div>
</div>

app/views/modals/_sign_up_success_inactive_content.html.erb
<h5 class="teal-text text-darken-3 fw-200">Hi <%= name %> We sent an email with a confirmation link to <span class="teal-text text-darken-4"><%= email %></span></h4>
<h5 class="teal-text text-darken-3 fw-200">Please click on the link to activate your account.</h4>

app/views/modals/login.js.erb
var case_it = "<%= case_it %>";
console.log("case is :" + case_it);
//controller=>sessions,action=>new,success/failure -> here meaningless
if(case_it == "sessions_new_success"){
	//TITLE
	$("#login_title").html("Sign In").show();
	//CONTENT
	$("#login_content").html("<%= escape_javascript(render partial: 'modals/login_default_content.html.erb') %>").show();
	$("#login_forms").html("<%= escape_javascript(render partial: 'modals/login_forms.html.erb', locals: {resource: login_opts['resource']}) %>").show();
	$("#recaptcha_tags").html("<%= escape_javascript(render partial: 'modals/recaptcha_tags.html.erb') %>").show();
	//FOOTER
	$("#login_footer").html("<%= escape_javascript(render partial: 'modals/login_navigation_options.html.erb') %>").show();
}
else if(case_it == "sessions_create_success"){
	mark_all_input_fields_valid();
	$("#personalization").html("<%= escape_javascript(render partial: 'layouts/personalization.html.erb') %>");
	$("#login_title").html("Sign In Successfull !").show();
	$("#login_content").html("<%= escape_javascript(render partial:'modals/sign_in_success_content.html.erb' ) %>").show();
	$("#login_footer").html("<%= escape_javascript(render partial: 'modals/login_navigation_options.html.erb') %>").hide();
}
else if(case_it == "registrations_create_success"){
	mark_all_input_fields_valid();
	//TITLE
	$("#login_title").html("Sign Up Successfull");
	//CONTENT
	var resource_active = "<%= login_opts['resource'].active_for_authentication? %>";

	if(resource_active == "true"){
		$("#login_content").html("<%= escape_javascript(render partial: 'modals/sign_up_success_content.html.erb', locals: {name: login_opts['resource'].name, email: login_opts['resource'].email}) %>").show();
		window.location.href = "<%= profile_user_path(login_opts['resource'].id) %>";
		$("#login_footer").html("Redirecting you to your Profile").show();
	}
	else{
		$("#login_content").html("<%= escape_javascript(render partial: 'modals/sign_up_success_inactive_content.html.erb', locals: {name: login_opts['resource'].name, email: login_opts['resource'].email}) %>").show();
		//FOOTER
		$("#login_footer").html("<%= escape_javascript(render partial: 'modals/login_navigation_options.html.erb') %>").show();
		$("#show_sign_up").hide();
		$("#forgot_password").hide();
		$("#resend_confirmation_email").show();
	}
}
else if(case_it == "registrations_create_failed"){
	mark_all_input_fields_valid();
	<% login_opts['resource'].errors.each do |attrib,message| %>
		<% if attrib =~ /recaptcha/ %>
			show_modal_error_message("<%= escape_javascript(message) %>");	
		<% else %>
			var resource_name = "<%= login_opts['resource'].class.name.underscore %>";
			var field_id = resource_name + "_" + "<%= attrib %>";
			invalidate_input_field(field_id,"<%= message.html_safe %>");
		<% end %>
	<% end %>
	//should focus on the first invalid field.
}
else if(case_it == "registrations_edit_success"){
	$("#login_title").html("Edit Account Settings");
	$("#login_content").html("<%= escape_javascript(render partial:'modals/edit_account_content.html.erb', locals: {resource: login_opts['resource']} ) %>");
	hide_oauth();
	$("#login_footer").hide();
}
else if(case_it == "registrations_update_success"){
	$("#login_title").html("Account Settings Successfully Updated!");
	$("#login_content").html("<%= escape_javascript(render partial:'modals/edit_account_success_content.html.erb', locals: {resource: login_opts['resource']} ) %>");
	hide_oauth();
	$("#login_footer").hide();
}
else if(case_it == "registrations_update_failed"){
	//first make all fields valid.
	mark_all_input_fields_valid();
	<% login_opts['resource'].errors.each do |attrib,message| %>
		var resource_name = "<%= login_opts['resource'].class.name.underscore %>";
			var field_id = resource_name + "_" + "<%= attrib %>";
			invalidate_input_field(field_id,"<%= message.html_safe %>");
	<% end %>
}
else if(case_it == "passwords_new_success"){
	$("#login_title").show().html("Forgot Password");
	$("#login_content").html("<%= escape_javascript(render partial:'modals/forgot_password_content.html.erb', locals: {resource: login_opts['resource']}) %>").show();
	$("#login_footer").html("<%= escape_javascript(render partial: 'modals/login_navigation_options.html.erb') %>").show();
	toggle_oauth();
	toggle_sign_up_text("Sign In or Sign Up");
	$("#show_sign_up").show();
	$("#forgot_password").hide();
	$("#resend_confirmation_email").hide();
}
else if(case_it == "passwords_create_success"){
	$("#login_title").hide();
	$("#login_content").html("<%= escape_javascript(render partial:'modals/forgot_password_success_content.html.erb', locals: {resource: login_opts['resource']}) %>").show();
	$("#login_footer").hide();
}
else if(case_it == "passwords_create_failed"){
	<% login_opts['resource'].errors.each do |attrib,message| %>
		var resource_name = "<%= login_opts['resource'].class.name.underscore %>";
			var field_id = resource_name + "_" + "<%= attrib %>";
			invalidate_input_field(field_id,"<%= message.html_safe %>");
	<% end %>
}
else if(case_it == "confirmations_new_success"){
	$("#login_title").show().html("Resend Confirmation Email");
	$("#login_content").html("<%= escape_javascript(render partial:'modals/resend_confirmation_content.html.erb', locals: {resource: login_opts['resource']}) %>").show();
	$("#login_footer").html("<%= escape_javascript(render partial: 'modals/login_navigation_options.html.erb') %>").show();
	toggle_oauth();
	toggle_sign_up_text("Sign In or Sign Up");
	$("#show_sign_up").show();
	$("#forgot_password").hide();
	$("#resend_confirmation_email").hide();
}
else if(case_it == "confirmations_create_success"){
    $("#login_title").hide();
	$("#login_content").html("<%= escape_javascript(render partial:'modals/resend_confirmation_success_content.html.erb', locals: {resource: login_opts['resource']}) %>").show();
	$("#login_footer").hide();
}
else if(case_it == "confirmations_create_failed"){
	<% login_opts['resource'].errors.each do |attrib,message| %>
		var resource_name = "<%= login_opts['resource'].class.name.underscore %>";
			var field_id = resource_name + "_" + "<%= attrib %>";
			invalidate_input_field(field_id,"<%= message.html_safe %>");
	<% end %>
}
open_sign_in_modal_if_closed();

app/views/modals/old_loginjserb.erb
if(case_it === "sign_in"){
	//TITLE
	$("#login_title").html("Sign In");
	//CONTENT
	$("#login_content").html("<%= escape_javascript(render partial: 'modals/login_default_content.html.erb') %>");
	$("#login_forms").html("<%= escape_javascript(render partial: 'modals/login_forms.html.erb', locals: {user: login_opts['user']}) %>");
	$("#recaptcha_tags").html("<%= escape_javascript(render partial: 'modals/recaptcha_tags.html.erb') %>");
	//FOOTER.
	$("#login_footer").html("<%= escape_javascript(render partial: 'modals/login_navigation_options.html.erb') %>");
}
else if(case_it === "sign_up_failed"){
	//TITLE 
	$("#login_title").html("Sign Up Failed");
	//CONTENT
	//set the content to the error notification, and show the error notification
	
	//now some logic.
	<% if login_opts['failed_fields'].nil? || login_opts['failed_fields'].empty? %>
			
			$("#error_message_wrapper").show();
			$("#login_error_message").html("Your request didn't go through, try again in some time.");

	<% else %>
	      
	      //grecaptcha.reset();

			<% login_opts['failed_fields'].stringify_keys.each do |field,message| %>
				
				<% if field =~ /recaptcha/ %>

					
		      		$("#login_error_message").
		      		text("<%= escape_javascript(message)%>");
		      		$("#login_error_message").append("<p class=\"blue-grey-text text-darken-3 fw-500\">The Captcha looks like this.</p>  <img src=\"/assets/recaptcha_for_modal.gif\" height=\"100\"/>")
		      	<% else %>

		      		var label = $('label[for="user_<%= escape_javascript(field) %>"]');
		      		var input = $('#user_' + '<%= escape_javascript(field) %>');

		      		input.attr("class","invalid");
		      		input.attr("aria-invalid",true);
		      		label.attr("data-error","<%= escape_javascript(message[0]) %>");
		                  $("input[class~='valid']").each(function(index){
		                        $(this).prop("disabled",true);
		                  });
		                  

				<% end %>

			<% end %>

		

	<% end %>

}
else if(case_it === "sign_up_success"){
	//TITLE
	$("#login_title").html("Sign Up Successfull");
	//CONTENT
	$("#login_content").html("<%= escape_javascript(render partial: 'modals/sign_up_success_content.html.erb', locals: {name: login_opts['name'], email: login_opts['email']}) %>");
	//FOOTER
	$("#login_footer").html("<%= escape_javascript(render partial: 'modals/login_navigation_options.html.erb') %>");
	$("#show_sign_up").hide();
	$("#forgot_password").hide();
	$("#resend_confirmation_email").show();
}
else if(case_it === "sign_in_success"){
	$("#personalization").html("<%= escape_javascript(render partial: 'layouts/personalization.html.erb') %>");
	$("#login_title").html("Sign In Successfull !");
	$("#login_content").html("<%= escape_javascript(render partial:'modals/sign_in_success_content.html.erb' ) %>");
	$("#login_footer").html("<%= escape_javascript(render partial: 'modals/login_navigation_options.html.erb') %>");
	$("#show_sign_up").hide();
	$("#forgot_password").hide();
	$("#resend_confirmation_email").hide();
	
}
else if(case_it === "sign_in_failed"){
	
	<% if flash[:failure_message]=~/invalid/i %>
		//both are invalid, or one is blank or something.
		var input = $("#user_email");
		var label = $('label[for="user_email"]');
		input.attr("class","invalid");
		input.attr("aria-invalid",true);
		label.attr("data-error","Please check this field");
		input = $("#user_password");
		label = $('label[for="user_password"]');
		input.attr("class","invalid");
		input.attr("aria-invalid",true);
		label.attr("data-error","Please check this field.");
	<% elsif flash[:failure_message]=~/email/i %>
		//if the error is with the email, clear the password
		$("#user_password").val('');
		//remove its class as being either valid or invalid
		$('label[for="user_password"]').removeClass("valid invalid");
		//its aria-invalid, should be false.
		$('label[for="user_password"]').attr('aria-invalid',false);
		//remove the data-error.
		$('label[for="user_password"]').removeAttr('data-error');
		//assign the label and input field to be changed.
		var label = $('label[for="user_email"]');
		var input = $('#user_email');
		input.attr("class","invalid");
		input.attr("aria-invalid",true);
		label.attr("data-error","<%= escape_javascript(flash[:failure_message]) %>");
	<% else %>
		//make the email valid
		$('label[for="user_email"]').removeClass("invalid").addClass("valid");
		//remove the aria invalid from the label.
		$('label[for="user_email"]').attr('aria-invalid',false);
		//remove the data-error attribute.
		$('label[for="user_email"]').removeAttr('data-error');
		var label = $('label[for="user_password"]');
		var input = $('#user_password');
		input.attr("class","invalid");
		input.attr("aria-invalid",true);
		label.attr("data-error","<%= escape_javascript(flash[:failure_message]) %>");
	<% end %>	
	
}
else if(case_it === "forgot_password"){
	$("#login_title").hide().show().html("Forgot Password");
	$("#login_content").html("<%= escape_javascript(render partial:'modals/forgot_password_content.html.erb', locals: {resource: login_opts['resource']}) %>");
	$("#login_footer").html("<%= escape_javascript(render partial: 'modals/login_navigation_options.html.erb') %>");
	toggle_oauth();
	toggle_sign_up_text("Sign In or Sign Up");
	$("#show_sign_up").show();
	$("#forgot_password").hide();
	$("#resend_confirmation_email").hide();
}
else if(case_it === "forgot_password_success"){
	$("#login_title").hide();
	$("#login_content").html("<%= escape_javascript(render partial:'modals/forgot_password_success_content.html.erb', locals: {resource: login_opts['resource']}) %>");
	$("#login_footer").hide();
}
else if(case_it === "forgot_password_failed"){
	<% if !login_opts['resource'].nil? && !login_opts['resource'].errors.empty? %>
		<% login_opts['resource'].errors.each do |attr,message| %>
			<% if attr.to_s == "email" %>
				var label = $('label[for="user_email"]');
				var input = $('#user_email');
				input.attr("class","invalid");
				input.attr("aria-invalid",true);
				label.attr("data-error","<%= attr.to_s.capitalize + ' ' +message %>");
			<% end %>
		<% end %>
	<% else %>
		$("#error_message_wrapper").show();
		$("#login_error_message").html("Your request didn't go through, try again in some time.");
	<% end %>
}
else if(case_it === "resend_confirmation"){
	$("#login_title").hide().show().html("Resend Confirmation Email");
	$("#login_content").html("<%= escape_javascript(render partial:'modals/resend_confirmation_content.html.erb', locals: {resource: login_opts['resource']}) %>");
	$("#login_footer").html("<%= escape_javascript(render partial: 'modals/login_navigation_options.html.erb') %>");
	toggle_oauth();
	toggle_sign_up_text("Sign In or Sign Up");
	$("#show_sign_up").show();
	$("#forgot_password").hide();
	$("#resend_confirmation_email").hide();
}
else if(case_it === "resend_confirmation_success"){
	$("#login_title").hide();
	$("#login_content").html("<%= escape_javascript(render partial:'modals/resend_confirmation_success_content.html.erb', locals: {resource: login_opts['resource']}) %>");
	$("#login_footer").hide();
}
else if(case_it === "resend_confirmation_failed"){
	<% if !login_opts['resource'].nil? && !login_opts['resource'].errors.empty? %>
		<% login_opts['resource'].errors.each do |attr,message| %>
			<% if attr.to_s == "email" %>
				var label = $('label[for="user_email"]');
				var input = $('#user_email');
				input.attr("class","invalid");
				input.attr("aria-invalid",true);
				label.attr("data-error","<%= attr.to_s.capitalize + ' ' +message %>");
			<% end %>
		<% end %>
	<% else %>
		$("#error_message_wrapper").show();
		$("#login_error_message").html("Your request didn't go through, try again in some time.");
	<% end %>
}
else if(case_it === "edit_account"){
	$("#login_title").html("Edit Account Settings");
	$("#login_content").html("<%= escape_javascript(render partial:'modals/edit_account_content.html.erb', locals: {resource: login_opts['resource']} ) %>");
	hide_oauth();
	$("#login_footer").hide();
}

<!--<%= render :partial => '/corners/corner_invites_publish_add_remove_stats.html.erb', locals:{c: corner, p: show_permissions, corner_id: corner.id.to_s} %>-->