config/routes.rb
Rails.application.routes.draw do
  get 'images/home' , :action => "home", :controller => "images"
  
  get 'images/azure_sas_uri', :action => "azure_sas_uri", :controller => "images"
  post 'images/azure_success', :action => "azure_success", :controller => "images"

  get 'login/new'

  get 'elements/build'

  get 'element/build'

  resources :units
  
  resources :lists, except: [:index,:new,:create,:show,:edit,:update] do 
    collection do 
      get 'element_spam_list'
    end
  end

  get 'categories/search'

  resources :tests, only: [:index,:new,:create,:show,:edit,:update] do
    collection do 
      get 'change'
    end
  end

  root 'home#index'

  resources :categories do 
    collection do 
      get 'search/:q', :action => "search", :as => 'search'
    end
  end

  

  resources :corners do 
    
  end

  resources :elements do 
    collection do 
      post 'edit_image'
    end
  end

  resources :reports, only: [:new]

  resources :home, only: [:index]

  

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" , :registrations => "users/registrations", :confirmations => "users/confirmations", :passwords => "users/passwords", :sessions => "users/sessions"}

  resources :users, except: [:show, :edit, :update, :destroy, :index, :new, :create] do

    collection do
        get 'sign_in_failed','email_exists','nickname_exists','password_strength','oauth_sign_in_failed','email_matches_current'
    end

    get 'profile', on: :member
  
  end

  

  resources :topics do 
    collection do
      get 'search/:q', :action => "search", :as => 'search'
    end
  end

end

app/views/layouts/_personalization.html.erb
<% if current_user %>
  <!-- we store it in the sign out link -->
  <li><%= link_to "Account", profile_user_path(current_user.id) %></li>
  <li><%= link_to('Sign Out', destroy_user_session_path, :method => :delete, id: "sign_out") %>      </li> 
  <li><%= link_to('New Corner', new_corner_path)  %></li>
<% else %>
  <li id="sign_in_nav_option"><a href="#" id="c_sign_in">Sign In</a></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wordjelly</title>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %>_controller">
<%= Gon::Base.render_data %>
<!-- layout vars -->
<!-- end -->
<div class="row">
    <div class="navbar-fixed">
      <nav class="teal">
        <div class="nav-wrapper">
          <a href="/" class="brand-logo">WordJelly
          
            <div class="preloader-wrapper small active m-5-left" style="vertical-align:middle; height:18px; width:18px; display:none;" id="progress_circle">
              <div class="spinner-layer spinner-white-only">
                <div class="circle-clipper left">
                  <div class="circle"></div>
                </div><div class="gap-patch">
                  <div class="circle"></div>
                </div><div class="circle-clipper right">
                  <div class="circle"></div>
                </div>
              </div>
            </div>
          

          </a>

          <ul class="right hide-on-med-and-down">
            <li><%= link_to "Latest Corner",corners_path %></li>
            <li><%= link_to "new image upload",new_test_path %></li>
            <li><a href="#">WP Plugin</a></li>
            <li><a href="components.html">Popular</a></li>
            <span id="personalization">
             <%= render '/layouts/personalization.html.erb' %>
            </span>
          </ul>
        </div>
    </nav>
  </div>
</div>

<div class="container" style="width:70%">
<%= yield %>
</div>
<%= render :partial => "/modals/ajax_error_modal.html.erb" %>
<%= render '/modals/sign_in_needed_modal.html.erb' %>
<%= render '/users/profiles/users_list_modal.html.erb' %>

<div class="filler">
<!-- adding this icon here because otherwise it doesnt get loaded for the ajax error modal ,since modals are display:none initially -->
<i class="mdi-content-clear" style="height:0px;width:0px;"></i>
</div>
<footer class="page-footer black">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">WJ</h5>
        <p class="grey-text text-lighten-4">Find You</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2014 Copyright Text
    </div>
  </div>
</footer>


</body>
<!--- footer -->

</html>